/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qu9t0bwyvXq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function PriceList() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-background">
      <Card className="w-full max-w-md p-6 space-y-4">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>AviShifo Pricing</CardTitle>
            <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
              Back to Home
            </Link>
          </div>
          <CardDescription>Choose a plan that fits your needs.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4">
            <div className="grid gap-2 border rounded-lg p-4">
              <div className="flex items-center justify-between">
                <h3 className="text-2xl font-bold">Basic</h3>
                <div className="text-4xl font-bold">$9</div>
              </div>
              <p className="text-muted-foreground">Per month</p>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  10 GB storage
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  1 user
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  Basic support
                </li>
              </ul>
              <Button className="w-full bg-primary text-primary-foreground">Subscribe</Button>
            </div>
            <div className="grid gap-2 border rounded-lg p-4">
              <div className="flex items-center justify-between">
                <h3 className="text-2xl font-bold">Pro</h3>
                <div className="text-4xl font-bold">$19</div>
              </div>
              <p className="text-muted-foreground">Per month</p>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  50 GB storage
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  5 users
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  Priority support
                </li>
              </ul>
              <Button className="w-full bg-primary text-primary-foreground">Subscribe</Button>
            </div>
            <div className="grid gap-2 border rounded-lg p-4">
              <div className="flex items-center justify-between">
                <h3 className="text-2xl font-bold">Enterprise</h3>
                <div className="text-4xl font-bold">$49</div>
              </div>
              <p className="text-muted-foreground">Per month</p>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  Unlimited storage
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  Unlimited users
                </li>
                <li className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4 fill-primary" />
                  Dedicated support
                </li>
              </ul>
              <Button className="w-full bg-primary text-primary-foreground">Subscribe</Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
